language: cpp
compiler: gcc

os:
  - linux
  - osx

matrix:
  allow_failures:
  fast_finish: true

env:
  global:
  matrix:
    # - export NODE_VERSION="0.12"
    - export NODE_VERSION="4"
    - export NODE_VERSION="5"
    - export NODE_VERSION="6"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; sudo apt-get update -qq; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - gcc --version
  - g++ --version
  - npm install node-gyp -g
  - npm install -g coveralls
  - npm install -g istanbul

before_script:
script:
  - npm install
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

# notifications:
#   webhooks:
#     branch: master
#     urls:
#       - https://webhooks.gitter.im/e/20bdfb25eb44f4600ce9
#     on_success: always
#     on_failure: always
#     on_start: false
#
