environment:
  matrix:
    # - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

matrix:
  allow_failures:
    - nodejs_version: "4"

platform:
  - x86
  - x64

image: Visual Studio 2015
install:
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  - ps: "ls \"C:/Program Files (x86)/Windows Kits\""
  - ps: "ls \"C:/Program Files (x86)/Windows Kits/10\""
  - ps: "ls \"C:/Program Files (x86)/Windows Kits/10/bin\""
  - ps: "ls \"C:/Program Files (x86)/Windows Kits/10/bin/x64\""
  - ps: "ls \"C:/Program Files (x86)/Windows Kits/10/bin/x86\""
  - ps: "ls \"C:/Program Files (x86)/Windows Kits/10/bin/arm\""
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g node-gyp
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
