environment:
  matrix:
    # - nodejs_version: "0.12"
    - nodejs_version: "6"
    - nodejs_version: "4"
    - nodejs_version: "5"

matrix:
  allow_failures:
    - nodejs_version: "4"

platform:
  - x86
  - x64

image: Visual Studio 2015
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:NO_ARCH="true"
  # install modules
  - npm install -g node-gyp
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - node -e "console.log(`${process.versions}\n${process.platform}\n${process.arch}\nNO_ARCH ${process.env.NO_ARCH}\n`)"
  # run tests
  - npm test

# Don't actually build.
build: off
