/*
c++
-Wl,-force_load,/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libopenssl.a
-Wl,-force_load,/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libv8_base.a
-Wl,-search_paths_first
-mmacosx-version-min=10.5
-arch
x86_64
-L/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release

-o
"/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/node"

/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/debug-agent.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/async-wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/env.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/fs_event_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/cares_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/handle_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/js_stream.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_buffer.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_constants.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_contextify.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_file.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_http_parser.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_javascript.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_main.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_os.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_revert.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_util.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_v8.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_stat_watcher.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_watchdog.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_zlib.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_i18n.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/pipe_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/signal_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/spawn_sync.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/string_bytes.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/stream_base.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/stream_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/tcp_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/timer_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/tty_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/process_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/udp_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/uv.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/util.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/string_search.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_crypto.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_crypto_bio.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_crypto_clienthello.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/tls_wrap.o
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/obj.target/node/src/node_dtrace.o

/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libcares.a
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libv8_libplatform.a
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libopenssl.a
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libzlib.a
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libhttp_parser.a
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libuv.a
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libv8_base.a
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libv8_libbase.a
/Users/jefe/repos/platform-tools/test/fixtures/sources/smoke/node/out/Release/libv8_snapshot.a
-framework
CoreFoundation
-lm
*/
